
- name: Add nginx repo for helm
  command: |
    chmod 600 /home/centos/.kube/config && helm repo add nginx-stable https://helm.nginx.com/stable && helm repo update
  when: is_centos

- name: Add prometheus repo for helm
  command: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update
  when: is_centos

- name: Add grafana repo for helm
  command: |
    helm repo add grafana https://grafana.github.io/helm-charts && helm repo update
  when: is_centos
