
- name: Add nginx repo for helm
  command: |
    helm repo add nginx-stable https://helm.nginx.com/stable
  when: is_centos

- name: Add prometheus repo for helm
  command: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  when: is_centos

- name: Add grafana repo for helm
  command: |
    helm repo add grafana https://grafana.github.io/helm-charts
  when: is_centos

- name: Update repos for helm
  command: |
    helm repo update
  when: is_centos
